In [1]:
import os, sys
import numpy as np
import pandas as pd
import librosa as lr
import csv
import matplotlib.pyplot as plt
from glob import glob
np.set_printoptions(threshold=sys.maxsize)

In [2]:
data_dir = '/Users/jungwookim/Desktop/Organized_final'
dirs = sorted(os.listdir(data_dir))

# This would print all the files and directories
for file in dirs:
    print(file);


.DS_Store
000001_Serum_Bass_BA Ampology [CFBass]_0.wav
000002_Serum_Bass_BA Ampology [CFBass]_12.wav
000003_Serum_Bass_BA Ampology [CFBass]_24.wav
000004_Serum_Bass_BA Ampology [CFBass]_36.wav
000005_Serum_Bass_BA Ampology [CFBass]_48.wav
000006_Serum_Bass_BA Ampology [CFBass]_60.wav
000007_Serum_Bass_BA Ampology [CFBass]_72.wav
000008_Serum_Bass_BA Ampology [CFBass]_84.wav
000009_Serum_Bass_BA Ampology [CFBass]_96.wav
000010_Serum_Bass_BA Ampology [CFBass]_108.wav
000011_Serum_Bass_BA Ampology [CFBass]_120.wav
000012_Serum_Bass_BA Analog Pluck [SN]_0.wav
000013_Serum_Bass_BA Analog Pluck [SN]_12.wav
000014_Serum_Bass_BA Analog Pluck [SN]_24.wav
000015_Serum_Bass_BA Analog Pluck [SN]_36.wav
000016_Serum_Bass_BA Analog Pluck [SN]_48.wav
000017_Serum_Bass_BA Analog Pluck [SN]_60.wav
000018_Serum_Bass_BA Analog Pluck [SN]_72.wav
000019_Serum_Bass_BA Analog Pluck [SN]_84.wav
000020_Serum_Bass_BA Analog Pluck [SN]_96.wav
000021_Serum_Bass_BA Analog Pluck [SN]_108.wav
000022_Serum_Bass_BA An

In [3]:
audio_files = glob(data_dir + '/*.wav')

In [4]:
len(audio_files)

1320

In [5]:
audio, sr = lr.load(audio_files[1319],sr=48000)
time = np.arange(0, len(audio)) / sr


In [6]:
#rms 1d array
rms_array = np.empty((len(audio_files), 1))
iter = 0
for file in range(0,len(audio_files), 1):
    audio, sr = lr.load(audio_files[file])
    rms =  lr.feature.rms(y = audio, frame_length = len(audio))
    rms_array[iter] = np.average(rms)
    iter = iter + 1
rms_array

array([[3.95270102e-02],
       [7.08618667e-03],
       [8.76483843e-02],
       [5.29578514e-02],
       [1.61607280e-01],
       [3.31436060e-02],
       [8.41856375e-02],
       [5.23214601e-02],
       [2.49667261e-02],
       [9.27726328e-02],
       [1.71648692e-02],
       [5.24830213e-03],
       [3.91357578e-02],
       [8.31348971e-02],
       [9.63587984e-02],
       [4.78391573e-02],
       [2.21313834e-01],
       [7.86682144e-02],
       [6.29105866e-02],
       [7.48896599e-02],
       [3.45850876e-03],
       [7.87243918e-02],
       [5.61632328e-02],
       [1.63591072e-01],
       [7.80430138e-02],
       [1.41286820e-01],
       [1.17718764e-01],
       [1.40509397e-01],
       [4.42346297e-02],
       [9.04841498e-02],
       [4.02399451e-02],
       [1.25585720e-02],
       [1.47493541e-01],
       [8.57785791e-02],
       [2.64922436e-02],
       [5.69745190e-02],
       [6.73297495e-02],
       [1.04512498e-01],
       [1.74310684e-01],
       [6.94126412e-02],


In [7]:
import csv

In [8]:
#mfcc 2d array
mfcc_array = np.empty((len(audio_files), 20))
iter = 0
for file in range(0,len(audio_files), 1):
    audio, sr = lr.load(audio_files[file])
    mfcc =  lr.feature.mfcc(y=audio, sr=48000)
    mfcc_array[iter] = np.average(mfcc, axis=1)
    iter = iter + 1

mfcc_array

array([[-5.71457703e+02,  1.13128014e+01,  3.77431726e+00,
         3.86948752e+00,  2.85839415e+00,  2.84998465e+00,
         2.41011667e+00,  2.16100955e+00,  1.75425255e+00,
         2.05618668e+00,  2.63563180e+00,  3.22894764e+00,
         3.36956310e+00,  3.41338444e+00,  3.19385910e+00,
         2.53238344e+00,  1.66868508e+00,  1.14222503e+00,
         8.97717297e-01,  6.85558796e-01],
       [-5.86054321e+02,  5.26761169e+01, -4.33056335e+01,
        -6.79992485e+00,  2.25208130e+01, -1.46474581e+01,
        -2.56944828e+01, -4.52409792e+00, -1.97846934e-01,
        -8.35693455e+00, -7.54850483e+00,  1.93840206e+00,
        -9.05473709e+00,  1.92756450e+00,  2.15884781e+00,
         3.68409514e+00, -1.41623468e+01,  4.45546532e+00,
         1.40466130e+00,  4.05515051e+00],
       [-6.78019348e+02, -1.19884291e+01,  2.25535822e+00,
         8.87485409e+00, -1.54283495e+01,  1.41353035e+01,
        -6.39023590e+00, -4.91438580e+00,  1.30246000e+01,
        -1.51511555e+01,  9.6

In [ ]:
#Spectral Centroid  use this one parameter 1d array
cent_array = np.empty((len(audio_files), 1))
iter = 0
for file in range(0,len(audio_files), 1):
    audio, sr = lr.load(audio_files[file])
    cent = lr.feature.spectral_centroid(y=audio, sr=48000)
    cent_array[iter] = np.average(cent)
    iter = iter + 1
cent_array

In [11]:
#Spectral bandwidth 1d array
bandwidth_array = np.empty((len(audio_files), 1))
iter = 0
for file in range(0,len(audio_files), 1):
    audio, sr = lr.load(audio_files[file])
    bandwidth = lr.feature.spectral_bandwidth(y=audio, sr=48000)
    bandwidth_array[iter] = np.average(bandwidth)
    iter = iter + 1
print(bandwidth_array)

[[2993.61896281]
 [3570.12853061]
 [3433.80393255]
 [3696.28699444]
 [3914.06121434]
 [1164.46171103]
 [3253.53216904]
 [2077.80280897]
 [2432.10691318]
 [2827.94335027]]


In [12]:
#spectral contrast 6 band 2d
contrast_array = np.empty((len(audio_files), 7))
iter = 0
for file in range(0,len(audio_files), 1):
    audio, sr = lr.load(audio_files[file])
    S = np.abs(lr.stft(audio))
    contrast = lr.feature.spectral_contrast(S=S, sr=48000)
    contrast_array[iter] = np.average(contrast,axis=1)
    iter = iter + 1

print(contrast_array)

[[31.63067254 14.50731787 18.01741685 17.23112705 17.87972082 16.06948795
  24.8935767 ]
 [27.85184838  8.53539817 13.51213557 15.50451817 33.04382204 27.78618069
  35.92717601]
 [25.23561018 19.39884301 19.29792373 22.40819454 23.03972148 21.16766041
  27.36636969]
 [26.4493532   8.5868377  25.04945201 24.50057334 27.85675599 25.69454804
  30.72717756]
 [27.05981169  8.46985865 11.25459306 27.70322025 27.70674203 27.84724018
  31.89997102]
 [26.29444748  8.20181654 11.11602348 11.53621099 12.50074343 12.72201523
  24.96795715]
 [26.22981564  9.23416681 17.21627557 18.33228342 19.45424248 33.86190593
  37.11308289]
 [24.58041995  9.25634088 10.11230357 11.98116806 12.74662932 12.38514608
  26.30874589]
 [24.9783558   9.91014622 17.10116344 19.38106995 20.93247247 18.4954675
  40.80494771]
 [25.91988669 10.77482877 12.31085102 12.25452516 13.59875135 12.70954513
  24.14371911]]


In [13]:
#spectral rolloff 1d array
rolloff_array = np.empty((len(audio_files), 1))
iter = 0
for file in range(0,len(audio_files), 1):
    audio, sr = lr.load(audio_files[file])
    #Appriximate Maximum Frequencies with roll_percent=0.85
    rolloff = lr.feature.spectral_rolloff(y=audio, sr=48000)
    rolloff_array[iter] = np.average(rolloff)  
    iter = iter + 1
print(rolloff_array)

[[4188.15104167]
 [7506.61892361]
 [5994.24913194]
 [7156.68402778]
 [8415.69010417]
 [ 303.27690972]
 [8376.30208333]
 [1588.54166667]
 [8423.50260417]
 [2971.24565972]]


In [14]:
#for file in range(0,len(audio_files), 1):
    #audio, sr = lr.load(audio_files[file])
    #Appriximate Minimum Frequencies with roll_percent=0.85
    #rolloff = librosa.feature.spectral_rolloff(y=y, sr=sr, roll_percent=0.1)

In [15]:
#spectral flatness 1d
flatness_array = np.empty((len(audio_files), 1))
iter = 0
for file in range(0,len(audio_files), 1):
    audio, sr = lr.load(audio_files[file])
    flatness = lr.feature.spectral_flatness(y=audio)
    flatness_array[iter] = np.average(flatness)
    iter = iter + 1
print(flatness_array)

[[2.82603200e-04]
 [9.17019934e-05]
 [4.93187166e-04]
 [1.90753664e-04]
 [4.06692008e-04]
 [1.17263453e-05]
 [7.76158195e-05]
 [8.24028539e-05]
 [6.24282766e-05]
 [2.06916570e-03]]


In [18]:
# 1d spectral centroiad + 2d Mfcc(multiple of mfcc values thats why we call it 2d array)a
a=np.concatenate((rms_array, mfcc_array, cent_array, bandwidth_array, contrast_array, rolloff_array, flatness_array), axis=1)

In [19]:
mfccFile = open('mfccFile.csv', mode='w')
writer = csv.writer(mfccFile, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
writer.writerow(["rms","mfcc1", "mfcc2", "mfcc3", "mfcc4", "mfcc5", "mfcc6", "mfcc7", "mfcc8", "mfcc9", "mfcc10", "mfcc11", "mfcc12", "mfcc13", "mfcc14", "mfcc15", "mfcc16", "mfcc17", "mfcc18", "mfcc19", "mfcc20","centroid","bandwidth","contrast1","contrast2","contrast3","contrast4","contrast5","contrast6","contrast7","rolloff","flatness"])
writer.writerows(a)
mfccFile.close()